# Generated by Django 3.1.6 on 2021-02-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=225)),
                ('recipe_name', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=20)),
                ('cuisine', models.CharField(max_length=200)),
                ('ingredients', models.TextField(max_length=20000)),
                ('cooking_method', models.TextField(max_length=20000)),
                ('serving', models.CharField(max_length=20)),
            ],
        ),
    ]
