# Generated by Django 3.1.5 on 2021-01-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=225)),
                ('recipe_name', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=20)),
                ('cuisine', models.CharField(max_length=200)),
                ('ingredients', models.TextField(max_length=20000)),
                ('cooking_method', models.TextField(max_length=20000)),
                ('serving', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default=0, max_length=100)),
                ('email', models.EmailField(max_length=60, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
            ],
        ),
    ]
